import type { IRArg, IRField, IRSchema, IRType } from './ir.js';
import { CLIENT_EMITS } from './clients.js';
import type { ClientKind } from './clients.js';
import { argTsType, inputTsType, leafTsType, typenameTsType } from './ts-types.js';
import type { ScalarPrelude } from './scalars.js';

const HEADER = `/* eslint-disable */
// AUTO-GENERATED BY buildql. DO NOT EDIT.
// Re-run \`npx buildql generate\` after changing the schema.
`;

/** Names the generated module always pulls from the package root. */
const CORE_IMPORTS = [
  'argSpec',
  'include',
  'leafField',
  'leafFieldArgs',
  'makeFragment',
  'makeMutation',
  'makeQuery',
  'makeSubscription',
  'objectField',
  'objectFieldArgs',
  'on',
  'skip',
  'spread',
];

/**
 * Client names that come from the package root itself (`createClient`) are merged into the
 * single root import and re-sorted rather than emitted as a second `from 'buildql'` line,
 * so the default output stays byte-identical to what buildql generated before this option
 * existed. `$` and `v` stay pinned to the end of the list, as they always were.
 */
function importBlock(client: ClientKind): string {
  const { module, names } = CLIENT_EMITS[client];
  const fromRoot = module === 'buildql' ? [...CORE_IMPORTS, ...names].sort() : [...CORE_IMPORTS].sort();
  const root = `import {\n${fromRoot.map((n) => `  ${n},`).join('\n')}\n  $,\n  v,\n} from 'buildql';\n`;
  if (!module || module === 'buildql') return root;
  return `${root}import { ${names.join(', ')} } from '${module}';\n`;
}

function reexportBlock(client: ClientKind): string {
  const list = ['$', 'v', 'on', 'spread', 'include', 'skip', ...CLIENT_EMITS[client].names];
  return `export { ${list.join(', ')} };\nexport type { Operation } from 'buildql';\n`;
}

/**
 * The `import type` lines and type aliases contributed by the `scalars` config. They sit
 * between the runtime import and the generated types, so an alias can reference another alias
 * (or itself, for a recursive JSON type) and every type map below can reference all of them.
 *
 * Imports are grouped by module, and modules and names are each sorted, so the same config
 * always produces the same bytes — a generated module that is committed to a repo must not
 * churn on iteration order. `import type` rather than a value import keeps the generated
 * module free of any *runtime* dependency on the user's type module, which is what allows it
 * to be published as a package whose type sources are only a devDependency.
 */
function scalarPreludeBlock(prelude: ScalarPrelude): string {
  const byModule = new Map<string, Set<string>>();
  for (const { name, from } of prelude.imports) {
    const names = byModule.get(from) ?? new Set<string>();
    names.add(name);
    byModule.set(from, names);
  }
  // Plain `<`/`>` rather than `localeCompare`: this ordering must not vary with the host
  // machine's locale, or the same config would emit different bytes on different machines.
  const lines = [...byModule.entries()]
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(
      ([from, names]) =>
        `import type { ${[...names].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0)).join(', ')} } from '${from}';`,
    );
  const decls = [...prelude.declarations]
    .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))
    .map((d) => `export type ${d.name} = ${d.body};`);
  if (lines.length === 0 && decls.length === 0) return '';
  return `${[...lines, ...decls].join('\n')}\n`;
}

/** Every name the generated module already binds, before the scalar prelude adds its own. */
function reservedNames(ir: IRSchema, client: ClientKind): Set<string> {
  const names = new Set<string>([
    ...CORE_IMPORTS,
    ...CLIENT_EMITS[client].names,
    '$',
    'v',
    'Operation',
    'query',
  ]);
  if (ir.mutationType) names.add('mutation');
  if (ir.subscriptionType) names.add('subscription');
  for (const t of ir.types) {
    // Scalar types emit no binding of their own — mapping the scalar `JSON` to a type also
    // named `JSON` is fine, and is in fact the obvious thing for a user to write.
    if (t.kind === 'scalar') continue;
    names.add(t.name);
    if (t.kind === 'enum') names.add(`${t.name}Values`);
    if (t.kind === 'object' || t.kind === 'interface' || t.kind === 'union') {
      names.add(`${lowerFirst(t.name)}Fragment`);
    }
  }
  return names;
}

/**
 * The `scalars` config can name any TypeScript type it likes, including one this emitter
 * already binds — `export type Money = ...` next to the schema's own `Money` input object is a
 * duplicate-identifier error reported against a generated file the user never wrote, hundreds
 * of lines from the config entry that caused it. Fail here instead, naming the collision.
 */
function assertNoScalarNameCollisions(ir: IRSchema, client: ClientKind): void {
  const reserved = reservedNames(ir, client);
  const declared = [
    ...ir.scalarPrelude.imports.map((i) => i.name),
    ...ir.scalarPrelude.declarations.map((d) => d.name),
  ];
  for (const name of declared) {
    if (reserved.has(name)) {
      throw new Error(
        `buildql: a "scalars" entry maps to a TypeScript type named "${name}", which the generated ` +
          `module already binds. Give it a different "name" in your buildql.config.*.`,
      );
    }
  }
}

function lowerFirst(s: string): string {
  return s.charAt(0).toLowerCase() + s.slice(1);
}

function wrapLiteral(wrap: readonly ('l' | '!')[]): string {
  return `[${wrap.map((w) => `'${w}'`).join(', ')}]`;
}

function argSpec(field: IRField, ir: IRSchema): string {
  const gqlEntries = field.args.map((a) => `${a.name}: '${a.gqlType}'`).join(', ');
  const enumKeys = field.args.filter((a) => a.type.kind === 'enum').map((a) => `'${a.name}'`);
  const enumArg = enumKeys.length > 0 ? `, [${enumKeys.join(', ')}]` : '';
  return `argSpec<${argTsType(field, ir)}>({ ${gqlEntries} }${enumArg})`;
}

function emitField(field: IRField, ir: IRSchema): string {
  const wrap = wrapLiteral(field.type.wrap);
  const isComposite =
    field.type.kind === 'object' || field.type.kind === 'interface' || field.type.kind === 'union';

  if (!isComposite) {
    const ts = leafTsType(field.type, ir);
    if (field.args.length === 0) {
      return `  ${field.name}: leafField<'${field.name}', ${wrap}, ${ts}>('${field.name}', ${wrap}),`;
    }
    // `leafFieldArgs` cannot infer its result type `T`, and TypeScript has no partial
    // explicit type arguments — so all four are written out.
    return `  ${field.name}: leafFieldArgs<'${field.name}', ${wrap}, ${ts}, ${argTsType(field, ir)}>('${field.name}', ${wrap}, ${argSpec(field, ir)}),`;
  }

  // Getters defer resolution so cyclic type references work.
  if (field.args.length === 0) {
    return `  get ${field.name}() { return objectField('${field.name}', ${wrap}, ${field.type.name}) },`;
  }
  return `  get ${field.name}() { return objectFieldArgs('${field.name}', ${wrap}, ${field.type.name}, ${argSpec(field, ir)}) },`;
}

function emitEnum(t: IRType): string {
  const members = t.enumValues.map((v) => `  ${v}: '${v}',`).join('\n');
  const union = t.enumValues.map((v) => `'${v}'`).join(' | ') || 'never';
  return `export const ${t.name}Values = {\n${members}\n} as const;\nexport type ${t.name} = ${union};\n`;
}

function emitInput(t: IRType, ir: IRSchema): string {
  const fields = t.inputFields
    .map((f: IRArg) => `  ${f.name}${f.optional ? '?' : ''}: ${inputTsType(f.type, ir)};`)
    .join('\n');
  return `export interface ${t.name} {\n${fields}\n}\n`;
}

function emitTypeMap(t: IRType, ir: IRSchema): string {
  const body = t.fields.map((f) => emitField(f, ir)).join('\n');
  const typename = `  __typename: leafField<'__typename', ['!'], ${typenameTsType(t)}>('__typename', ['!']),`;
  return `export const ${t.name} = {\n${typename}\n${body}\n};\n`;
}

export function emit(ir: IRSchema, client: ClientKind = 'buildql'): string {
  assertNoScalarNameCollisions(ir, client);
  const parts: string[] = [HEADER, importBlock(client)];
  // Pushed only when non-empty: `parts` is joined with '\n', so an empty string here would
  // add a blank line and break the byte-identical-by-default promise for string-form configs.
  const prelude = scalarPreludeBlock(ir.scalarPrelude);
  if (prelude.length > 0) parts.push(prelude);

  for (const t of ir.types.filter((t) => t.kind === 'enum')) parts.push(emitEnum(t));
  for (const t of ir.types.filter((t) => t.kind === 'input')) parts.push(emitInput(t, ir));

  const composite = ir.types.filter(
    (t) => t.kind === 'object' || t.kind === 'interface' || t.kind === 'union',
  );
  for (const t of composite) parts.push(emitTypeMap(t, ir));

  parts.push(`export const query = makeQuery(${ir.queryType});`);
  if (ir.mutationType) parts.push(`export const mutation = makeMutation(${ir.mutationType});`);
  if (ir.subscriptionType)
    parts.push(`export const subscription = makeSubscription(${ir.subscriptionType});`);

  for (const t of composite) {
    parts.push(`export const ${lowerFirst(t.name)}Fragment = makeFragment('${t.name}', ${t.name});`);
  }

  parts.push(reexportBlock(client));
  return parts.join('\n');
}
