import type { IRArg, IRField, IRSchema, IRType } from './ir.js';
import { CLIENT_EMITS } from './clients.js';
import type { ClientKind } from './clients.js';
import { argTsType, inputTsType, leafTsType, typenameTsType } from './ts-types.js';

const HEADER = `/* eslint-disable */
// AUTO-GENERATED BY buildql. DO NOT EDIT.
// Re-run \`npx buildql generate\` after changing the schema.
`;

/** Names the generated module always pulls from the package root. */
const CORE_IMPORTS = [
  'argSpec',
  'include',
  'leafField',
  'leafFieldArgs',
  'makeFragment',
  'makeMutation',
  'makeQuery',
  'makeSubscription',
  'objectField',
  'objectFieldArgs',
  'on',
  'skip',
  'spread',
];

/**
 * Client names that come from the package root itself (`createClient`) are merged into the
 * single root import and re-sorted rather than emitted as a second `from 'buildql'` line,
 * so the default output stays byte-identical to what buildql generated before this option
 * existed. `$` and `v` stay pinned to the end of the list, as they always were.
 */
function importBlock(client: ClientKind): string {
  const { module, names } = CLIENT_EMITS[client];
  const fromRoot = module === 'buildql' ? [...CORE_IMPORTS, ...names].sort() : [...CORE_IMPORTS].sort();
  const root = `import {\n${fromRoot.map((n) => `  ${n},`).join('\n')}\n  $,\n  v,\n} from 'buildql';\n`;
  if (!module || module === 'buildql') return root;
  return `${root}import { ${names.join(', ')} } from '${module}';\n`;
}

function reexportBlock(client: ClientKind): string {
  const list = ['$', 'v', 'on', 'spread', 'include', 'skip', ...CLIENT_EMITS[client].names];
  return `export { ${list.join(', ')} };\nexport type { Operation } from 'buildql';\n`;
}

function lowerFirst(s: string): string {
  return s.charAt(0).toLowerCase() + s.slice(1);
}

function wrapLiteral(wrap: readonly ('l' | '!')[]): string {
  return `[${wrap.map((w) => `'${w}'`).join(', ')}]`;
}

function argSpec(field: IRField, ir: IRSchema): string {
  const gqlEntries = field.args.map((a) => `${a.name}: '${a.gqlType}'`).join(', ');
  const enumKeys = field.args.filter((a) => a.type.kind === 'enum').map((a) => `'${a.name}'`);
  const enumArg = enumKeys.length > 0 ? `, [${enumKeys.join(', ')}]` : '';
  return `argSpec<${argTsType(field, ir)}>({ ${gqlEntries} }${enumArg})`;
}

function emitField(field: IRField, ir: IRSchema): string {
  const wrap = wrapLiteral(field.type.wrap);
  const isComposite =
    field.type.kind === 'object' || field.type.kind === 'interface' || field.type.kind === 'union';

  if (!isComposite) {
    const ts = leafTsType(field.type, ir);
    if (field.args.length === 0) {
      return `  ${field.name}: leafField<'${field.name}', ${wrap}, ${ts}>('${field.name}', ${wrap}),`;
    }
    // `leafFieldArgs` cannot infer its result type `T`, and TypeScript has no partial
    // explicit type arguments — so all four are written out.
    return `  ${field.name}: leafFieldArgs<'${field.name}', ${wrap}, ${ts}, ${argTsType(field, ir)}>('${field.name}', ${wrap}, ${argSpec(field, ir)}),`;
  }

  // Getters defer resolution so cyclic type references work.
  if (field.args.length === 0) {
    return `  get ${field.name}() { return objectField('${field.name}', ${wrap}, ${field.type.name}) },`;
  }
  return `  get ${field.name}() { return objectFieldArgs('${field.name}', ${wrap}, ${field.type.name}, ${argSpec(field, ir)}) },`;
}

function emitEnum(t: IRType): string {
  const members = t.enumValues.map((v) => `  ${v}: '${v}',`).join('\n');
  const union = t.enumValues.map((v) => `'${v}'`).join(' | ') || 'never';
  return `export const ${t.name}Values = {\n${members}\n} as const;\nexport type ${t.name} = ${union};\n`;
}

function emitInput(t: IRType, ir: IRSchema): string {
  const fields = t.inputFields
    .map((f: IRArg) => `  ${f.name}${f.optional ? '?' : ''}: ${inputTsType(f.type, ir)};`)
    .join('\n');
  return `export interface ${t.name} {\n${fields}\n}\n`;
}

function emitTypeMap(t: IRType, ir: IRSchema): string {
  const body = t.fields.map((f) => emitField(f, ir)).join('\n');
  const typename = `  __typename: leafField<'__typename', ['!'], ${typenameTsType(t)}>('__typename', ['!']),`;
  return `export const ${t.name} = {\n${typename}\n${body}\n};\n`;
}

export function emit(ir: IRSchema, client: ClientKind = 'buildql'): string {
  const parts: string[] = [HEADER, importBlock(client)];

  for (const t of ir.types.filter((t) => t.kind === 'enum')) parts.push(emitEnum(t));
  for (const t of ir.types.filter((t) => t.kind === 'input')) parts.push(emitInput(t, ir));

  const composite = ir.types.filter(
    (t) => t.kind === 'object' || t.kind === 'interface' || t.kind === 'union',
  );
  for (const t of composite) parts.push(emitTypeMap(t, ir));

  parts.push(`export const query = makeQuery(${ir.queryType});`);
  if (ir.mutationType) parts.push(`export const mutation = makeMutation(${ir.mutationType});`);
  if (ir.subscriptionType)
    parts.push(`export const subscription = makeSubscription(${ir.subscriptionType});`);

  for (const t of composite) {
    parts.push(`export const ${lowerFirst(t.name)}Fragment = makeFragment('${t.name}', ${t.name});`);
  }

  parts.push(reexportBlock(client));
  return parts.join('\n');
}
