import type { IRArg, IRField, IRSchema, IRType, IRTypeRef } from './ir.js';
import { UNKNOWN_SCALAR } from './scalars.js';

const HEADER = `/* eslint-disable */
// AUTO-GENERATED BY buildql. DO NOT EDIT.
// Re-run \`npx buildql generate\` after changing the schema.
`;

const IMPORTS = `import {
  args,
  createClient,
  include,
  leaf,
  leafArgs,
  makeFragment,
  makeMutation,
  makeQuery,
  makeSubscription,
  object,
  objectArgs,
  on,
  skip,
  spread,
  $,
  v,
} from 'buildql';
`;

const REEXPORTS = `export { $, v, on, spread, include, skip, createClient };
export type { Operation } from 'buildql';
`;

function lowerFirst(s: string): string {
  return s.charAt(0).toLowerCase() + s.slice(1);
}

function wrapLiteral(wrap: readonly ('l' | '!')[]): string {
  return `[${wrap.map((w) => `'${w}'`).join(', ')}]`;
}

/** The TypeScript type a *leaf* (scalar/enum) named type maps to. */
function leafTsType(ref: IRTypeRef, ir: IRSchema): string {
  if (ref.kind === 'enum') return ref.name;
  return ir.scalars[ref.name] ?? UNKNOWN_SCALAR;
}

/** The TypeScript type of an *input* position, wrappers included. */
function inputTsType(ref: IRTypeRef, ir: IRSchema): string {
  const base = ref.kind === 'input' || ref.kind === 'enum' ? ref.name : (ir.scalars[ref.name] ?? UNKNOWN_SCALAR);
  // Walk the wrapper inner-to-outer, mirroring Apply<> from the runtime.
  let out = base;
  const toks = [...ref.wrap].reverse();
  let nonNull = false;
  for (const tok of toks) {
    if (tok === '!') {
      nonNull = true;
    } else {
      out = nonNull ? `${out}[]` : `(${out} | null)[]`;
      nonNull = false;
    }
  }
  return nonNull ? out : `${out} | null`;
}

/** The TS type of a field's argument object, e.g. `{ name: string; age?: number }`. */
function argTsType(field: IRField, ir: IRSchema): string {
  const entries = field.args
    .map((a) => `${a.name}${a.optional ? '?' : ''}: ${inputTsType(a.type, ir)}`)
    .join('; ');
  return `{ ${entries} }`;
}

function argSpec(field: IRField, ir: IRSchema): string {
  const gqlEntries = field.args.map((a) => `${a.name}: '${a.gqlType}'`).join(', ');
  const enumKeys = field.args.filter((a) => a.type.kind === 'enum').map((a) => `'${a.name}'`);
  const enumArg = enumKeys.length > 0 ? `, [${enumKeys.join(', ')}]` : '';
  return `args<${argTsType(field, ir)}>({ ${gqlEntries} }${enumArg})`;
}

function emitField(field: IRField, ir: IRSchema): string {
  const wrap = wrapLiteral(field.type.wrap);
  const isComposite =
    field.type.kind === 'object' || field.type.kind === 'interface' || field.type.kind === 'union';

  if (!isComposite) {
    const ts = leafTsType(field.type, ir);
    if (field.args.length === 0) {
      return `  ${field.name}: leaf<'${field.name}', ${wrap}, ${ts}>('${field.name}', ${wrap}),`;
    }
    // `leafArgs` cannot infer its result type `T`, and TypeScript has no partial
    // explicit type arguments — so all four are written out.
    return `  ${field.name}: leafArgs<'${field.name}', ${wrap}, ${ts}, ${argTsType(field, ir)}>('${field.name}', ${wrap}, ${argSpec(field, ir)}),`;
  }

  // Getters defer resolution so cyclic type references work.
  if (field.args.length === 0) {
    return `  get ${field.name}() { return object('${field.name}', ${wrap}, ${field.type.name}) },`;
  }
  return `  get ${field.name}() { return objectArgs('${field.name}', ${wrap}, ${field.type.name}, ${argSpec(field, ir)}) },`;
}

function emitEnum(t: IRType): string {
  const members = t.enumValues.map((v) => `  ${v}: '${v}',`).join('\n');
  const union = t.enumValues.map((v) => `'${v}'`).join(' | ') || 'never';
  return `export const ${t.name}Values = {\n${members}\n} as const;\nexport type ${t.name} = ${union};\n`;
}

function emitInput(t: IRType, ir: IRSchema): string {
  const fields = t.inputFields
    .map((f: IRArg) => `  ${f.name}${f.optional ? '?' : ''}: ${inputTsType(f.type, ir)};`)
    .join('\n');
  return `export interface ${t.name} {\n${fields}\n}\n`;
}

/**
 * The TS type of `__typename` for a type map. A union or interface can resolve to
 * one of several `possibleTypes` at runtime, so it must be typed as their union —
 * typing it as the abstract type's own name (e.g. `'Pet'`, a value the server never
 * actually sends) makes `__typename` collide with every `on()` branch's literal and
 * collapses the field to `never` wherever the two are intersected (see `Selected`
 * in `src/types/select.ts`). Concrete object types keep their own single literal name.
 */
function typenameTsType(t: IRType): string {
  if (t.kind === 'union' || t.kind === 'interface') {
    if (t.possibleTypes.length === 0) return 'string';
    return t.possibleTypes.map((p) => `'${p}'`).join(' | ');
  }
  return `'${t.name}'`;
}

function emitTypeMap(t: IRType, ir: IRSchema): string {
  const body = t.fields.map((f) => emitField(f, ir)).join('\n');
  const typename = `  __typename: leaf<'__typename', ['!'], ${typenameTsType(t)}>('__typename', ['!']),`;
  return `export const ${t.name} = {\n${typename}\n${body}\n};\n`;
}

/**
 * Every custom scalar in the schema with no entry in `ir.scalars` — these fall back
 * to `UNKNOWN_SCALAR` (`unknown`) in the generated output, which silently drops all
 * type safety for that field (and, in argument position, all argument checking). The
 * CLI surfaces this list as a warning so the degradation is loud rather than silent.
 */
export function unmappedScalars(ir: IRSchema): string[] {
  const names = new Set<string>();
  for (const t of ir.types) {
    if (t.kind === 'scalar' && !(t.name in ir.scalars)) names.add(t.name);
  }
  return [...names].sort();
}

export function emit(ir: IRSchema): string {
  const parts: string[] = [HEADER, IMPORTS];

  for (const t of ir.types.filter((t) => t.kind === 'enum')) parts.push(emitEnum(t));
  for (const t of ir.types.filter((t) => t.kind === 'input')) parts.push(emitInput(t, ir));

  const composite = ir.types.filter(
    (t) => t.kind === 'object' || t.kind === 'interface' || t.kind === 'union',
  );
  for (const t of composite) parts.push(emitTypeMap(t, ir));

  parts.push(`export const query = makeQuery(${ir.queryType});`);
  if (ir.mutationType) parts.push(`export const mutation = makeMutation(${ir.mutationType});`);
  if (ir.subscriptionType) parts.push(`export const subscription = makeSubscription(${ir.subscriptionType});`);

  for (const t of composite) {
    parts.push(`export const ${lowerFirst(t.name)}Fragment = makeFragment('${t.name}', ${t.name});`);
  }

  parts.push(REEXPORTS);
  return parts.join('\n');
}
